### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by chrisbrandow** [akpw/Obj-C-FusionTables#3] opened 2016-09-12 22:29 UTC
I apologize if this is something trivial, but it seems like a cocoa pod dependency issue(?)

I got the following output after trying `pod install`, or `pod update`

```
Update all pods
Updating local specs repositories

CocoaPods 1.1.0.rc.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Obj-C-FusionTables (2.0.3)
Installing gtm-http-fetcher (1.0.141)

[!] Error installing gtm-http-fetcher
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force http://gtm-http-fetcher.googlecode.com/svn/trunk/ -r 141 /var/folders/wj/vw9nhkgd6nvfv62fk0kzy84m0000gp/T/d20160912-34438-13qzljm

svn: E170013: Unable to connect to a repository at URL 'http://gtm-http-fetcher.googlecode.com/svn/trunk'
svn: E160013: '/svn/trunk' path not found
```

**Comment by akpw** [comment] 2016-09-17 04:48
This indeed is a broken dependency, apparently caused by Google ditching `gtm-http-fetcher`'s old location without fixing the related [gtm-oauth2 pod](https://cocoapods.org/?q=gtm-oauth2). 

A (reasonably) future-proof fix would be via switching the dependency to [GTMSessionFetcher](https://github.com/google/gtm-session-fetcher).

Will look at resolving in a day or two.

**Comment by akpw** [comment] 2016-09-18 14:44
Resolved

**Closed as completed by akpw** 2016-09-18 14:44 UTC
